apiVersion: v1
kind: Secret
metadata:
  name: my-service-db-secret
type: Opaque
stringData:
  # For testing purposes only. Do not use these credentials in production.
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
